source 'https://rubygems.org'

gem 'mojinizer', '~> 0.2'
gem 'nokogiri', '~> 1.6'
gem 'pry'

# Make sure you have FTS5 enabled for your SQLite3.
# e.g. `brew reinstall sqlite3 --with-fts5`
gem 'sqlite3', '~> 1.3'
